CREATE TABLE IF NOT EXISTS PRODUCT(
	PRODUCT_ID       INTEGER PRIMARY KEY ASC,
	PRODUCT_NAME     TEXT,
	STATUS           TEXT,
	UOM1             TEXT,
	UOM2             TEXT,
	CONVFACT         INTEGER,
	CATEGORY_CODE    TEXT,
	SUBCATEGORY_ID   TEXT,
	BRAND            TEXT,
	FLAVOUR          TEXT,
	SAFETYSTOCK      REAL,
	COMMISSION       TEXT,
	CREATE_DATE      TEXT,
	UPDATE_DATE      TEXT,
	VOLUMN           REAL,
	NETWEIGHT        REAL,
	GROSSWEIGHT      REAL,
	PACKING          TEXT,
	PRODUCT_TYPE_ID  INTEGER,
	PRODUCT_CODE     TEXT,
	CREATE_USER      TEXT,
	UPDATE_USER      TEXT,
	PRODUCT_TYPE     TEXT,
	SUB_CAT          TEXT
);

CREATE TABLE IF NOT EXISTS SALES_ORDER(
	SALE_ORDER_ID 	INTEGER ,
	MY_SYNC_STATUS 	INTEGER ,
	SHOP_ID         INTEGER,
	ORDER_TYPE      TEXT,
	ORDER_NUMBER    TEXT,
	INVOICE_NUMBER  TEXT,
	ORDER_DATE      TEXT,
	CUSTOMER_ID     INTEGER,
	STAFF_ID        INTEGER,
	DELIVERY_CODE   TEXT,
	AMOUNT          REAL,
	DISCOUNT        REAL,
	PROMO_CODE      TEXT,
	TOTAL           REAL,
	STATE           INTEGER,
	CREATE_USER     TEXT,
	UPDATE_USER     TEXT,
	CREATE_DATE     TEXT,
	UPDATE_DATE     TEXT,
	IS_VISIT_PLAN   TEXT,
	IS_SEND         INTEGER,
	SYN_STATUS      INTEGER,
	LOCAL_STATE     INTEGER ,
	PRIMARY KEY (SALE_ORDER_ID, MY_SYNC_STATUS)
);

CREATE TABLE IF NOT EXISTS SALES_ORDER_DETAIL(
	SALES_ORDER_DETAIL_ID  INTEGER ,
	MY_SYNC_STATUS 	       INTEGER ,
	PRODUCT_ID             INTEGER,
	QUANTITY               REAL,
	PRICE_ID               REAL,
	DISCOUNT_PERCENTAGE    REAL,
	DISCOUNT_AMOUNT        REAL,
	IS_FREE_ITEM           INTEGER,
	PROMOTION_CODE         TEXT,
	AMOUNT                 REAL,
	REASON_CODE            TEXT,
	SALE_ORDER_ID          INTEGER,
	PRICE                  REAL,
	CREATE_USER            TEXT,
	UPDATE_USER            TEXT,
	CREATE_DATE            REAL,
	UPDATE_DATE            REAL,
	ORDER_DATE             REAL,
	MAX_QUANTITY_FREE      INTEGER,
	LOCAL_STATE     INTEGER  ,
	PRIMARY KEY (SALES_ORDER_DETAIL_ID, MY_SYNC_STATUS)
);

CREATE TABLE IF NOT EXISTS SHOP(
	SHOP_ID			INTEGER PRIMARY KEY ASC,
	SHOP_CODE 		TEXT,
	SHOP_NAME 		TEXT,
	PARENT_SHOP_ID 	INTEGER,
	STREET 			TEXT,
	WARD 			TEXT,
	DISTRICT 		TEXT,
	PROVINCE 		TEXT,
	AREA_CODE 		TEXT,
	COUNTRY 		TEXT,
	PHONE 			TEXT,
	TELEPHONE 		TEXT,
	SHOP_TYPE 		INTEGER,
	CREATE_USER 	TEXT,
	UPDATE_USER 	TEXT,
	CREATE_DATE 	TEXT,
	UPDATE_DATE 	TEXT,
	CHANNEL_TYPE_ID INTEGER,
	EMAIL 			TEXT
);

CREATE TABLE IF NOT EXISTS STOCK_TOTAL(
	STOCK_TOTAL_ID 		INTEGER PRIMARY KEY ASC,
	OWNER_ID 			INTEGER,
	OWNER_TYPE 			INTEGER,
	PRODUCT_ID 			INTEGER,
	DESCRIPTION 		TEXT,
	CATEGORY_CODE 		TEXT,
	SUB_CATEGORY 		TEXT,
	BRAND 				TEXT,
	FLAVOUR 			TEXT,
	CHECK_DATE 			TEXT,
	QUANTITY 			REAL,
	AVAILABLE_QUANTITY 	INTEGER,
	CREATE_USER 		TEXT,
	UPDATE_USER 		TEXT,
	CREATE_DATE 		TEXT,
	UPDATE_DATE 		TEXT
);

CREATE TABLE IF NOT EXISTS VISIT_PLAN(			
	VISIT_PLAN_ID 		INTEGER PRIMARY KEY ASC,
	SHOP_ID 			INTEGER,
	STAFF_ID 			INTEGER,
	CUSTOMER_ID 		INTEGER,
	START_DATE 			TEXT,
	END_DATE 			TEXT,	
	FREQ 				TEXT,
	WEEK_SALE 			TEXT,
	MONDAY 				INTEGER,
	TUESDAY 			INTEGER,
	WEDNESDAY 			INTEGER,
	THURSDAY 			INTEGER,
	FRIDAY 				INTEGER,
	SATURDAY 			INTEGER,
	SUNDAY 				INTEGER,
	ACTIVE 				INTEGER,
	SEQ2 				INTEGER,
	SEQ3 				INTEGER,
	SEQ4 				INTEGER,
	SEQ5 				INTEGER,
	SEQ6 				INTEGER,
	SEQ7 				INTEGER,
	SEQ8 				INTEGER,
	ISNEWOUTLET 		INTEGER,
	UPDATE_DATE 		TEXT,
	CREATE_DATE 		TEXT,	
	CREATE_USER 		TEXT,
	UPDATE_USER 		TEXT
);

CREATE TABLE IF NOT EXISTS CUSTOMER
(
	CUSTOMER_ID         INTEGER PRIMARY KEY ASC,
	CUSTOMER_CODE       TEXT,
	CUSTOMER_NAME       TEXT,
	SHOP_ID             TEXT,
	COUNTRY             TEXT,
	AREA_CODE           TEXT,
	STREET              TEXT,
	HOUSENUMBER         TEXT,
	PHONE               TEXT,
	CREATE_DATE         TEXT,
	UPDATE_DATE         TEXT,
	POSTAL_CODE         TEXT,
	CONTACT_PERSON      TEXT,
	TAX_CODE            TEXT,
	MOBILEPHONE         TEXT,
	LOCATION            TEXT,
	CUSTOMER_TYPE_ID    INTEGER,
	LOYALTY             INTEGER,
	CREATE_USER         TEXT,
	UPDATE_USER         TEXT,
	DISLAY              TEXT,
	LAST_APPROVE_ORDER  TEXT,
	LAST_ORDER          TEXT
);

CREATE TABLE IF NOT EXISTS DISPLAY_PROGRAME
(
	DISPLAY_PROGRAME_ID    INTEGER PRIMARY KEY ASC,
	DISPLAY_PROGRAME_CODE  TEXT,
	DISPLAY_PROGRAME_NAME  TEXT,
	STATUS                 INTEGER,
	FROM_DATE              TEXT,
	TO_DATE                TEXT,
	OBJTARGET              REAL,
	RELATION               TEXT,
	CREATE_DATE            TEXT,
	UPDATE_DATE            TEXT,
	CREATE_USER            TEXT,
	UPDATE_USER            TEXT,
	CAT                    TEXT,
	PERCENT_FINO           REAL
);

CREATE TABLE IF NOT EXISTS DISPLAY_PROGRAME_DETAIL
(
	DISPLAY_PROGRAME_DETAIL_ID  INTEGER,
	DISPLAY_PROGRAME_ID         INTEGER,
	PRODUCT_ID                  INTEGER,
	QUALTITY                    INTEGER,
	BRAND_GROUP                 TEXT,
	CATEGORY_CODE               TEXT,
	CREATE_USER                 TEXT,
	UPDATE_USER                 TEXT,
	CREATE_DATE                 TEXT,
	UPDATE_DATE                 TEXT
);

CREATE TABLE IF NOT EXISTS DISPLAY_PROGRAME_LEVEL
(
	DISPLAY_PROGRAME_CODE  TEXT,
	LEVEL_CODE             TEXT,
	AMOUNT                 INTEGER,
	FROM_DATE              TEXT,
	TO_DATE                TEXT,
	STATUS                 TEXT
);

CREATE TABLE IF NOT EXISTS DISPLAY_PROGRAME_PRODUCT
(
	DISPLAY_PROGRAME_CODE  TEXT,
	PRODUCT_CODE           TEXT,
	CATEGORY               TEXT,
	FROM_DATE              TEXT,
	TO_DATE                TEXT,
	STATUS                 TEXT
);

CREATE TABLE IF NOT EXISTS DISPLAY_PROGRAME_SUB_CAT
(
	DISPLAY_PROGRAME_SUB_CAT_ID  INTEGER,
	DISPLAY_PROGRAME_ID          INTEGER,
	SUB_CAT                      TEXT,
	STATUS                       INTEGER
);

CREATE TABLE IF NOT EXISTS LOG_TABLE
(
	LOG_ID 		TEXT PRIMARY KEY,
	VALUE 		TEXT,
	USER_ID 	TEXT,
	STATE 		TEXT
);

CREATE TABLE IF NOT EXISTS PRICE
(
	PRICE_ID 	INTEGER PRIMARY KEY AUTOINCREMENT, 
	PRODUCT_ID 	INTEGER,
	STATUS 		TEXT,
	FROM_DATE 	TEXT,
	TO_DATE 	TEXT,
	CREATE_USER TEXT,
	UPDATE_USER TEXT,
	CREATE_DATE TEXT,
	UPDATE_DATE TEXT,
	PRICE 		REAL
);

CREATE TABLE IF NOT EXISTS FOCUS_PROGRAME
(
  FOCUS_PROGRAME_ID    INTEGER PRIMARY KEY,
  FOCUS_PROGRAME_CODE  TEXT,
  FOCUS_PROGRAME_NAME  TEXT,
  STATUS               TEXT,
  FROM_DATE            TEXT,
  TO_DATE              TEXT,
  CREATE_USER          TEXT,
  UPDATE_USER          TEXT,
  CREATE_DATE          TEXT,
  UPDATE_DATE          TEXT
);

CREATE TABLE IF NOT EXISTS FOCUS_PROGRAME_DETAIL
(
  FOCUS_PROGRAME_DETAIL_ID  INTEGER PRIMARY KEY,
  FOCUS_PROGRAME_ID         INTEGER,
  PRODUCT_ID                INTEGER,
  CREATE_USER               TEXT,
  UPDATE_USER               TEXT,
  CREATE_DATE               TEXT,
  UPDATE_DATE               TEXT
);

CREATE TABLE IF NOT EXISTS FOCUS_SHOP_MAP
(
  FOCUS_PROGRAME_ID  INTEGER,
  SHOP_ID            INTEGER,
  STATUS             INTEGER,
  FOCUS_SHOP_MAP_ID  INTEGER PRIMARY KEY,
  CREATE_DATE        TEXT,
  USER_UPDATE        TEXT,
  UPDATE_DATE        TEXT,
  UPDATE_USER        TEXT
);

CREATE TABLE IF NOT EXISTS PROMOTION_PROGRAME
(
  PROMOTION_PROGRAME_ID    INTEGER PRIMARY KEY,
  PROMOTION_PROGRAME_CODE  TEXT,
  PROMOTION_PROGRAME_NAME  TEXT,
  STATUS                   TEXT,
  TYPE                     TEXT,
  PRO_FORMAT               TEXT,
  FROM_DATE                TEXT,
  TO_DATE                  TEXT,
  RELATION                 INTEGER,
  SHOP_ID                  INTEGER,
  CUSTOMER_TYPE            TEXT,
  AREA_CODE                TEXT,
  CREATE_USER              TEXT,
  UPDATE_USER              TEXT,
  CREATE_DATE              TEXT,
  UPDATE_DATE              TEXT,
  MULTIPLE                 INTEGER
);

CREATE TABLE IF NOT EXISTS PROMOTION_PROGRAME_DETAIL
(
  PROMOTION_PRO_DETAIL_ID  INTEGER PRIMARY KEY,
  PROMOTION_PROGRAME_ID    INTEGER,
  PRODUCT_ID               INTEGER,
  SALE_QTY                 REAL,
  SALE_UOM                 TEXT,
  SALE_AMT                 REAL,
  DISC_AMT                 REAL,
  DISC_PER                 REAL,
  FREE_PRODUCT_ID          INTEGER,
  FREE_QTY                 REAL,
  FREE_UOM                 TEXT,
  CREATE_USER              TEXT,
  UPDATE_USER              TEXT,
  CREATE_DATE              TEXT,
  UPDATE_DATE              TEXT,
  REQUIRED                 INTEGER
);

CREATE TABLE IF NOT EXISTS SYN_TABLEDATA_LOG
(
  ID            INTEGER PRIMARY KEY AUTOINCREMENT,
  STAFF_ID      INTEGER,
  LAST_SYNDATE  TEXT,
  LAST_STATUS   INTEGER
);

CREATE TABLE IF NOT EXISTS CALL_SALE_CUSTOMER
(
  CALL_SALE_CUSTOMER_ID  INTEGER,
  STAFF_ID               INTEGER,
  CUSTOMER_ID            INTEGER,
  STATUS                 INTEGER,
  CREATE_DATE            TEXT,
  CREATE_USER            TEXT,
  NOTE                   TEXT,
  CURRENT_STATUS         TEXT
);

CREATE TABLE IF NOT EXISTS STAFF(
	STAFF_ID            INTEGER PRIMARY KEY ASC,
	STAFF_CODE          TEXT,
	NAME                TEXT,
	ADDRESS             TEXT,
	STREET              TEXT,
	COUNTRY             TEXT,
	PHONE               TEXT,
	MOBILE              TEXT,
	MAIL                TEXT,
	SEX                 TEXT,
	START_DATE          TEXT,
	EDUCATION_ID        TEXT,
	POSITION_ID         TEXT,
	CAT_ID              INTEGER,
	STAFF_OWNER_ID      INTEGER,
	BIRTHDAY            TEXT,
	SHOP_ID             INTEGER,
	AREA_CODE           TEXT,
	CREATE_USER         TEXT,
	UPDATE_USER         TEXT,
	CREATE_TIME         TEXT,
	UPDATE_TIME         TEXT,
	CHANNEL_TYPE_ID     INTEGER,
	STATUS              INTEGER,
	PASSWORD            TEXT,
	NUMBER_LOGIN_FAIL   INTEGER,
	LOCKSTATUS          INTEGER,
	PLAN                INTEGER,
	UPDATE_PLAN         TEXT,
	LAST_APPROVE_ORDER  TEXT,
	LAST_ORDER          TEXT
);